### ISSUE TITLE
Invalid SSL Certificate for https://beta.kontalk.net/

### ISSUE THREAD

**Issue by svrnwnsch** [kontalk/network#7]
If i open https://beta.kontalk.net/ I get an invalid ssl certificate (SSL_ERROR_BAD_CERT_DOMAIN) as the certifcate is only for the urls zeta.kontalk.net, kontalk.net

**Comment by daniele-athome** [comment]
That's because of the server migration. It's not an issue though: beta.kontalk.net it's not meant to be accessed on port 443 (for now). It'll be fixed automatically when Kontalk server will listen on that port.
