### ISSUE TITLE
Privacy notes

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/network#9]
Some notes for Google Play (mandatory in a few days; write a wiki page):

- [x] phone number given to 3rd parties (verification providers: Nexmo, Checkmobi) for verification only
- [x] hashed phone contacts sent to the server for matching (not stored)
- [x] roster list stored on server
- [x] public/private key

**Comment by daniele-athome** [comment]
Initial draft to be reviewed: https://github.com/kontalk/network/wiki/Privacy-notes

Key points:

* Very quick facts
* Straight to the point
* Be honest
* Do not get too technical

**Comment by webratte** [comment]
Should "Crash reporting/Analytics" not be a userpreference in stable relase?

For Alpha/Beta versions of course mandatory.

**Comment by daniele-athome** [comment]
Yes, I'll make it a user preference, but I'd prefer to set it as an opt-out preference, otherwise it's useless: the great part of Kontalk userbase will not even know what it is, and we need crash feedbacks from the general population.
